@startuml
actor Admin
actor Pelatih
actor Atlet
actor OrangTua

usecase "Pendaftaran Atlet" as UC1
usecase "Manajemen Jadwal" as UC2
usecase "Pemantauan Kehadiran" as UC3
usecase "Evaluasi Atlet" as UC4
usecase "Pelaporan Keuangan" as UC5
usecase "Melihat Hasil Evaluasi" as UC6
usecase "Membayar Pelatihan" as UC7

Admin --> UC1 : Mengelola
Admin --> UC2 : Mengatur Jadwal
Admin --> UC5 : Melihat Laporan

Pelatih --> UC2 : Mengatur Jadwal
Pelatih --> UC3 : Mencatat Kehadiran
Pelatih --> UC4 : Memberikan Evaluasi

Atlet --> UC3 : Memasukkan Kehadiran
Atlet --> UC4 : Melihat Evaluasi
Atlet --> UC7 : Melakukan Pembayaran

OrangTua --> UC6 : Memantau Evaluasi

@enduml
