@startuml
left to right direction
actor Admin
actor "Staff Gudang" as Staff

rectangle "Aplikasi Pengelolaan Data Barang" {
    Admin --> (Pengelolaan Data Barang)
    Admin --> (Pencatatan Transaksi)
    Admin --> (Pelaporan Stok)
    Admin --> (Pembaruan Stok)
    Staff --> (Pengelolaan Penerimaan Barang)
    Staff --> (Memantau Stok)
}

(Pengelolaan Data Barang) -right-> (Basis Data) : Menambah, mengubah, menghapus
(Pencatatan Transaksi) -down-> (Basis Data) : Transaksi masuk/keluar
(Pelaporan Stok) -left-> (Admin) : Menampilkan laporan real-time
(Pembaruan Stok) -right-> (Basis Data) : Stok otomatis diperbarui
(Pengelolaan Penerimaan Barang) -down-> (Basis Data) : Mencatat barang masuk
(Memantau Stok) -left-> (Staff) : Informasi stok terkini
@enduml
